
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Booksale extends javax.swing.JFrame 
{

    Statement stat;
    /**
     * Creates new form Booksale
     */
    public Booksale() 
    {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect() 
    {
        String dburl= "jdbc:ucanaccess://E://bookdatabase.accdb";

        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con= DriverManager.getConnection(dburl);
            System.out.println("Conncection Success");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
        }

        

        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ltitle = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        lauthor = new javax.swing.JLabel();
        lpub = new javax.swing.JLabel();
        lprice = new javax.swing.JLabel();
        lid = new javax.swing.JLabel();
        lqty = new javax.swing.JLabel();
        tauthor = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        tprice = new javax.swing.JTextField();
        tpub = new javax.swing.JTextField();
        Bcancel = new javax.swing.JButton();
        Bexit = new javax.swing.JButton();
        tqty = new javax.swing.JTextField();
        Bok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tsale = new javax.swing.JTable();
        Bview = new javax.swing.JButton();
        Bup = new javax.swing.JButton();
        Bdel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 176, 118));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18), new java.awt.Color(0, 0, 102))); // NOI18N

        Ltitle.setBackground(new java.awt.Color(0, 204, 255));
        Ltitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Ltitle.setForeground(new java.awt.Color(204, 102, 0));
        Ltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ltitle.setText("Jue's Book Store");

        lname.setBackground(new java.awt.Color(255, 255, 102));
        lname.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Book Name");

        lauthor.setBackground(new java.awt.Color(255, 255, 102));
        lauthor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lauthor.setForeground(new java.awt.Color(255, 255, 255));
        lauthor.setText("Author");

        lpub.setBackground(new java.awt.Color(255, 255, 102));
        lpub.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lpub.setForeground(new java.awt.Color(255, 255, 255));
        lpub.setText("Publisher");

        lprice.setBackground(new java.awt.Color(255, 255, 102));
        lprice.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lprice.setForeground(new java.awt.Color(255, 255, 255));
        lprice.setText("Price");

        lid.setBackground(new java.awt.Color(255, 255, 102));
        lid.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lid.setForeground(new java.awt.Color(255, 255, 255));
        lid.setText("Book ID");

        lqty.setBackground(new java.awt.Color(255, 255, 102));
        lqty.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lqty.setForeground(new java.awt.Color(255, 255, 255));
        lqty.setText("Quantity");

        tauthor.setBackground(new java.awt.Color(153, 204, 255));
        tauthor.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N

        tname.setBackground(new java.awt.Color(153, 204, 255));
        tname.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });

        tid.setBackground(new java.awt.Color(153, 204, 255));
        tid.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N

        tprice.setBackground(new java.awt.Color(153, 204, 255));
        tprice.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N

        tpub.setBackground(new java.awt.Color(153, 204, 255));
        tpub.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N

        Bcancel.setBackground(new java.awt.Color(102, 204, 255));
        Bcancel.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        Bcancel.setText("Cancel");
        Bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelActionPerformed(evt);
            }
        });

        Bexit.setBackground(new java.awt.Color(102, 204, 255));
        Bexit.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        Bexit.setText("Exit");
        Bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexitActionPerformed(evt);
            }
        });

        tqty.setBackground(new java.awt.Color(153, 204, 255));
        tqty.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N

        Bok.setBackground(new java.awt.Color(51, 204, 255));
        Bok.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        Bok.setText("OK");
        Bok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BokActionPerformed(evt);
            }
        });

        tsale.setBackground(new java.awt.Color(0, 204, 255));
        tsale.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tsale.setForeground(new java.awt.Color(255, 0, 102));
        tsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " BookID", "BookName", "Author", "Publisher", "Price", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tsale.setGridColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(tsale);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Bview.setBackground(new java.awt.Color(102, 255, 153));
        Bview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Bview.setForeground(new java.awt.Color(51, 51, 51));
        Bview.setText("View");
        Bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BviewActionPerformed(evt);
            }
        });

        Bup.setBackground(new java.awt.Color(102, 255, 153));
        Bup.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Bup.setForeground(new java.awt.Color(51, 51, 51));
        Bup.setText("Update");
        Bup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupActionPerformed(evt);
            }
        });

        Bdel.setBackground(new java.awt.Color(102, 255, 153));
        Bdel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Bdel.setForeground(new java.awt.Color(51, 51, 51));
        Bdel.setText("Delete");
        Bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(Ltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(tauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lqty, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lprice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpub, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tqty, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpub, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Bok, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(Bcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(Bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bview, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Ltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lpub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lprice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(lauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lqty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tqty, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bok, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bview, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bup, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupActionPerformed
        String id,bname,auth,pub,price,qty;
        
        id=tid.getText();
        bname=tname.getText();
        auth=tauthor.getText();
        pub=tpub.getText();
        price=tprice.getText();
        qty=tqty.getText();
        try 
        {
            pst=con.prepareStatement("update book set BookName='"+bname+"',Author='"+auth+"', Publisher='"+pub+"', Price='"+price+"',Quantity='"+qty+"' where ID='"+id+"'");
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Updated Book Successfully");
            
        } catch (SQLException ex) {
            Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BupActionPerformed

    private void BviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BviewActionPerformed
       int c;
        try 
        {
            pst= con.prepareStatement("select * from book");
            rs= pst.executeQuery();
            
            ResultSetMetaData rm=rs.getMetaData();
            c= rm.getColumnCount();
            
            DefaultTableModel model=(DefaultTableModel) tsale.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2= new Vector();
                for(int i=0; i<=c; i++)
                {
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("BookName"));
                    v2.add(rs.getString("Author"));
                    v2.add(rs.getString("Publisher"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("Quantity"));
                    
                }
                model.addRow(v2);
                
            }

            } catch (SQLException ex) 
            {
                Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }//GEN-LAST:event_BviewActionPerformed

    private void BokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BokActionPerformed
        // TODO add your handling code here:
        String id,bname,auth,pub,price,qty;
        
        id=tid.getText();
        bname=tname.getText();
        auth=tauthor.getText();
        pub=tpub.getText();
        price=tprice.getText();
        qty=tqty.getText();
        
        try 
        {
            pst=con.prepareStatement("insert into book (ID,BookName,Author,Publisher,Price,Quantity) values(?,?,?,?,?,?)");
            pst.setString(1, id);
            pst.setString(2, bname);
            pst.setString(3, auth);
            pst.setString(4, pub);
            pst.setString(5, price);
            pst.setString(6, qty);
            int k= pst.executeUpdate();
            
            if(k==1)
            {
                JOptionPane.showMessageDialog(this, "Insert Data Successfully");
                
                
            }
            
            } catch (SQLException ex) 
            {
                Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }//GEN-LAST:event_BokActionPerformed

    private void BexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_BexitActionPerformed

    private void BcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelActionPerformed
        // TODO add your handling code here:
        String id,bname,auth,pub;
        int price,qty;
        
        tid.setText("");
        tname.setText("");
        tauthor.setText("");
        tpub.setText("");
        tprice.setText("");
        tqty.setText("");
        

    }//GEN-LAST:event_BcancelActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void BdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdelActionPerformed
        // TODO add your handling code here:
        String id;
        
        id=tid.getText();
        
        
        try 
        {
            pst=con.prepareStatement("delete * from book where ID=?");
            pst.setString(1, id);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Deleted Book Successfully");
            
        } catch (SQLException ex) {
            Logger.getLogger(Booksale.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_BdelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booksale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booksale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booksale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booksale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booksale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcancel;
    private javax.swing.JButton Bdel;
    private javax.swing.JButton Bexit;
    private javax.swing.JButton Bok;
    private javax.swing.JButton Bup;
    private javax.swing.JButton Bview;
    private javax.swing.JLabel Ltitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lauthor;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lprice;
    private javax.swing.JLabel lpub;
    private javax.swing.JLabel lqty;
    private javax.swing.JTextField tauthor;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField tpub;
    private javax.swing.JTextField tqty;
    private javax.swing.JTable tsale;
    // End of variables declaration//GEN-END:variables
}
